# Generated by Django 4.0.1 on 2022-01-23 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_product_photo_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Kategoriya'),
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
